# Generated by Django 3.0.3 on 2020-06-27 08:22

import data_api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageIntervalMin', models.IntegerField()),
                ('ageIntervalMax', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
            ],
        ),
        migrations.CreateModel(
            name='Compaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('startDate', models.DateField(auto_now=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Requested', max_length=20)),
                ('compaignPicture', models.ImageField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('ageMin', models.IntegerField(blank=True, null=True)),
                ('ageMax', models.IntegerField(blank=True, null=True)),
                ('urlProduit', models.URLField(blank=True, null=True)),
                ('ageGroup', models.ManyToManyField(blank=True, to='data_api.AgeGroup')),
                ('announcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ManyToManyField(blank=True, to='data_api.City')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeImported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tags', models.CharField(blank=True, max_length=256, null=True)),
                ('episodesLoadingStatus', models.CharField(blank=True, default='Not initialized', max_length=20, null=True)),
                ('listenNotesId', models.CharField(blank=True, max_length=256, null=True)),
                ('genre', models.CharField(default='Other', max_length=256)),
                ('editor', models.CharField(max_length=256, null=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('podcastPicture', models.ImageField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(blank=True, null=True)),
                ('about', models.TextField()),
                ('public', models.CharField(max_length=256)),
                ('nb_episodes', models.IntegerField(blank=True, default=0, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('profilePicture', models.ImageField(blank=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PodcastStatGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plays', models.IntegerField()),
                ('nbEpisodes', models.IntegerField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendDate', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('readFlag', models.BooleanField(default=False)),
                ('attachedFile', models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('attachedFileName', models.TextField(blank=True, null=True)),
                ('compaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Compaign')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('updateDate', models.DateField(auto_now_add=True)),
                ('plays', models.IntegerField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.EpisodeImported')),
            ],
        ),
        migrations.AddField(
            model_name='episodeimported',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('listenNotesId', models.CharField(blank=True, max_length=256)),
                ('link', models.URLField(blank=True, null=True)),
                ('audio', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date_ms', models.DateTimeField(blank=True, default=None, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('audio_length_sec', models.IntegerField(blank=True, default=0, null=True)),
                ('explicit_content', models.BooleanField(blank=True, default=False, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast')),
            ],
        ),
        migrations.AddField(
            model_name='compaign',
            name='country',
            field=models.ManyToManyField(blank=True, to='data_api.Country'),
        ),
        migrations.AddField(
            model_name='compaign',
            name='educationLevel',
            field=models.ManyToManyField(blank=True, to='data_api.Education'),
        ),
        migrations.AddField(
            model_name='compaign',
            name='interests',
            field=models.ManyToManyField(blank=True, to='data_api.Interest'),
        ),
        migrations.AddField(
            model_name='compaign',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast'),
        ),
        migrations.AddField(
            model_name='compaign',
            name='targetGender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Gender'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Country'),
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('startDate', models.DateField(auto_now=True)),
                ('status', models.CharField(max_length=256)),
                ('Requesttext', models.TextField()),
                ('compaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Compaign')),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast')),
            ],
        )
    ]
