# Generated by Django 3.0.3 on 2020-07-22 17:46

import data_api.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageIntervalMin', models.IntegerField()),
                ('ageIntervalMax', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
            ],
        ),
        migrations.CreateModel(
            name='Compaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('startDate', models.DateField(auto_now=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='Créée', max_length=20)),
                ('statusNum', models.IntegerField(default=1)),
                ('plays', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('compaignPicture', models.ImageField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('audioFile', models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_audiofilename)),
                ('actionFor', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('adText', models.TextField(blank=True, max_length=2000, null=True)),
                ('pitch', models.TextField(blank=True, max_length=2000, null=True)),
                ('urlProduit', models.CharField(blank=True, max_length=40, null=True)),
                ('ageGroup', models.ManyToManyField(blank=True, to='data_api.AgeGroup')),
                ('announcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ManyToManyField(blank=True, null=True, to='data_api.City')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeImported',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=28)),
                ('sendDate', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('readFlag', models.BooleanField(default=False)),
                ('attachedFile', models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('attachedFileName', models.TextField(blank=True, null=True)),
                ('compaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Compaign')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('urlFeed', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
                ('nbEpisodes', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nbPlays', models.IntegerField()),
                ('price', models.IntegerField()),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40, null=True), blank=True, null=True, size=None)),
                ('editor', models.CharField(blank=True, max_length=128, null=True)),
                ('ageGroup', models.ManyToManyField(blank=True, null=True, to='data_api.AgeGroup')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ManyToManyField(blank=True, null=True, to='data_api.City')),
                ('country', models.ManyToManyField(blank=True, null=True, to='data_api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('profilePicture', models.ImageField(blank=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('plays', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Message')),
            ],
        ),
        migrations.CreateModel(
            name='PodcastStatGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plays', models.IntegerField()),
                ('nbEpisodes', models.IntegerField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast')),
            ],
        ),
        migrations.AddField(
            model_name='podcast',
            name='tags',
            field=models.ManyToManyField(blank=True, to='data_api.Tag'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='targetGender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Gender'),
        ),
        migrations.CreateModel(
            name='EpisodeStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('updateDate', models.DateField(auto_now_add=True)),
                ('plays', models.IntegerField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.EpisodeImported')),
            ],
        ),
        migrations.CreateModel(
            name='episodePodcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pubDate', models.DateField(auto_now=True)),
                ('audio', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.TextField(blank=True, max_length=400, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast')),
            ],
        ),
        migrations.AddField(
            model_name='episodeimported',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('listenNotesId', models.CharField(blank=True, max_length=256)),
                ('link', models.URLField(blank=True, null=True)),
                ('audio', models.URLField(blank=True, null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('pub_date_ms', models.DateTimeField(blank=True, default=None, null=True)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('audio_length_sec', models.IntegerField(blank=True, default=0, null=True)),
                ('explicit_content', models.BooleanField(blank=True, default=False, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast')),
            ],
        ),
        migrations.AddField(
            model_name='compaign',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.Country'),
        ),
        migrations.AddField(
            model_name='compaign',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast'),
        ),
        migrations.AddField(
            model_name='compaign',
            name='targetGender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Gender'),
        ),
        migrations.CreateModel(
            name='attached',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachedFile', models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('attachedFileName', models.TextField(blank=True, null=True)),
                ('compaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Compaign')),
            ],
        ),
    ]
