# Generated by Django 3.0.3 on 2020-06-27 08:33

import data_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaignAttachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachedFile', models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_filename)),
                ('attachedFileName', models.TextField(blank=True, null=True)),
                ('compaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naaa', to='data_api.Compaign')),
            ],
        ),
    ]
