# Generated by Django 3.0.3 on 2020-07-23 07:29

import data_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaign',
            name='audioFile',
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioFile', models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_audiofilename)),
                ('audioFileName', models.FileField(blank=True, max_length=200, null=True, upload_to='')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Message')),
            ],
        ),
    ]
