# Generated by Django 3.0.3 on 2020-06-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_auto_20200622_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageIntervalMin', models.IntegerField()),
                ('ageIntervalMax', models.IntegerField()),
                ('ageIntervalLabel', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='compaign',
            name='ageGroup',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.AgeGroup'),
        ),
    ]
