# Generated by Django 3.0.3 on 2020-07-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_auto_20200723_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audioFileName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
