# Generated by Django 3.0.3 on 2020-06-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0002_compaignattachedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='Education',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
