# Generated by Django 3.0.3 on 2020-07-23 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0003_auto_20200723_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Message'),
        ),
    ]
