# Generated by Django 3.0.3 on 2020-06-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0004_remove_education_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='status',
            field=models.CharField(default='Créée', max_length=20),
        ),
    ]
