# Generated by Django 3.0.3 on 2020-07-24 08:04

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0004_auto_20200723_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatePublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40, null=True), blank=True, null=True, size=None)),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Message')),
            ],
        ),
    ]
