# Generated by Django 3.0.3 on 2020-06-24 21:15

import data_api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0004_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='EducationLevel',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.Education'),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='compaignPicture',
            field=models.ImageField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_filename),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='podcast',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast'),
        ),
    ]
