# Generated by Django 3.0.3 on 2020-07-24 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0005_datepublication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DatePublication',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='date',
            old_name='categories',
            new_name='dates',
        ),
    ]
