# Generated by Django 3.0.3 on 2020-06-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0005_auto_20200628_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='urlProduit',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
