# Generated by Django 3.0.3 on 2020-06-25 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0006_auto_20200625_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compaign',
            old_name='EducationLevel',
            new_name='educationLevel',
        ),
    ]
