# Generated by Django 3.0.3 on 2020-07-24 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0006_auto_20200724_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='startDateValidated',
            field=models.DateField(auto_now=True),
        ),
    ]
