# Generated by Django 3.0.3 on 2020-07-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0007_compaign_startdatevalidated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='actionFor',
            field=models.IntegerField(),
        ),
    ]
