# Generated by Django 3.0.3 on 2020-06-25 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0007_auto_20200625_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaign',
            name='targetGender',
        ),
        migrations.AddField(
            model_name='compaign',
            name='targetGender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data_api.Gender'),
            preserve_default=False,
        ),
    ]
