# Generated by Django 3.0.3 on 2020-07-26 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0008_auto_20200725_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='status',
            field=models.CharField(choices=[(1, 'Demande'), (2, 'Devis'), (3, 'Pitch'), (4, '3nregistrement'), (5, 'Choix de date'), (6, 'En cours'), (7, 'Terminée')], default='Demande', max_length=20),
        ),
    ]
