# Generated by Django 3.0.3 on 2020-06-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0008_auto_20200625_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='compaign',
            name='interests',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.Interest'),
        ),
    ]
