# Generated by Django 3.0.3 on 2020-07-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0009_auto_20200726_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompaignStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
            ],
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='statusNum',
        ),
        migrations.AlterField(
            model_name='compaign',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.CompaignStatus'),
        ),
    ]
