# Generated by Django 3.0.3 on 2020-06-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0009_auto_20200625_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Country')),
            ],
        ),
        migrations.AddField(
            model_name='compaign',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.City'),
        ),
        migrations.AddField(
            model_name='compaign',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.Country'),
        ),
    ]
