# Generated by Django 3.0.3 on 2020-07-01 10:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0010_auto_20200701_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='ageInterval',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='podcast',
            name='city',
            field=models.ManyToManyField(blank=True, to='data_api.City'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='country',
            field=models.ManyToManyField(blank=True, to='data_api.Country'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='interests',
            field=models.ManyToManyField(blank=True, to='data_api.Interest'),
        ),
    ]
