# Generated by Django 3.0.3 on 2020-06-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0010_auto_20200625_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
