# Generated by Django 3.0.3 on 2020-07-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0010_auto_20200726_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaign',
            name='status',
        ),
    ]
