# Generated by Django 3.0.3 on 2020-07-26 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0011_remove_compaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.CompaignStatus'),
        ),
    ]
