# Generated by Django 3.0.3 on 2020-06-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0012_auto_20200625_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=52),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=52),
        ),
    ]
