# Generated by Django 3.0.3 on 2020-05-31 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0013_auto_20200525_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='episodesLoadingStatus',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
