# Generated by Django 3.0.3 on 2020-07-26 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_api', '0013_auto_20200726_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='messageFor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messageFor', to=settings.AUTH_USER_MODEL),
        ),
    ]
