# Generated by Django 3.0.3 on 2020-06-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0013_auto_20200625_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agegroup',
            old_name='ageIntervalLabel',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='Education',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Location',
            new_name='name',
        ),
    ]
