# Generated by Django 3.0.3 on 2020-06-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0014_auto_20200625_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='ageMax',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compaign',
            name='ageMin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
