# Generated by Django 3.0.3 on 2020-07-26 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_api', '0014_compaign_messagefor'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='actionFor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to=settings.AUTH_USER_MODEL),
        ),
    ]
