# Generated by Django 3.0.3 on 2020-07-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0014_auto_20200701_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='nbEpisodes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
