# Generated by Django 3.0.3 on 2020-07-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0015_auto_20200706_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='categories',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='podcast',
            name='editor',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
