# Generated by Django 3.0.3 on 2020-06-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0015_auto_20200531_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='Type',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='episodesLoadingStatus',
            field=models.CharField(blank=True, default='Not initialized', max_length=20, null=True),
        ),
    ]
