# Generated by Django 3.0.3 on 2020-06-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0015_auto_20200626_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='urlProduit',
            field=models.URLField(blank=True, null=True),
        ),
    ]
