# Generated by Django 3.0.3 on 2020-06-26 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0016_compaign_urlproduit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='targetGender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Gender'),
        ),
    ]
