# Generated by Django 3.0.3 on 2020-06-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0016_auto_20200602_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
