# Generated by Django 3.0.3 on 2020-07-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0016_auto_20200726_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='status',
            field=models.CharField(default='pending', max_length=25),
        ),
    ]
