# Generated by Django 3.0.3 on 2020-06-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0017_compaign_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='genre',
            field=models.CharField(default='Other', max_length=256),
        ),
    ]
