# Generated by Django 3.0.3 on 2020-06-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0017_auto_20200626_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='city',
            field=models.ManyToManyField(blank=True, to='data_api.City'),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='country',
            field=models.ManyToManyField(blank=True, to='data_api.Country'),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='educationLevel',
            field=models.ManyToManyField(blank=True, to='data_api.Education'),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='interests',
            field=models.ManyToManyField(blank=True, to='data_api.Interest'),
        ),
    ]
