# Generated by Django 3.0.3 on 2020-07-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0017_auto_20200707_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='episodePodcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pubDate', models.DateField(auto_now=True)),
                ('audio', models.CharField(blank=True, max_length=256, null=True)),
                ('image', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.TextField(blank=True, max_length=400, null=True)),
                ('duration', models.IntegerField()),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast')),
            ],
        ),
    ]
