# Generated by Django 3.0.3 on 2020-07-27 12:15

import data_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0017_audio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='audioFile',
            field=models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_audiofilename),
        ),

    ]
