# Generated by Django 3.0.3 on 2020-06-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0018_auto_20200626_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='ageGroup',
            field=models.ManyToManyField(blank=True, to='data_api.AgeGroup'),
        ),
    ]
