# Generated by Django 3.0.3 on 2020-07-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0018_auto_20200727_1215'),
    ]

    operations = [

        migrations.AddField(
            model_name='date',
            name='status',
            field=models.CharField(default='pending', max_length=25),
        ),
    ]
