# Generated by Django 3.0.3 on 2020-07-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0018_episodepodcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodepodcast',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
