# Generated by Django 3.0.3 on 2020-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0018_auto_20200612_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='tags',
            field=models.CharField(default='Podcast', max_length=256),
            preserve_default=False,
        ),
    ]
