# Generated by Django 3.0.3 on 2020-07-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0019_auto_20200707_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.City'),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.Country'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='urlFeed',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
