# Generated by Django 3.0.3 on 2020-07-27 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0019_auto_20200727_1348'),
    ]

    operations = [

        migrations.AddField(
            model_name='compaign',
            name='pubDate',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
