# Generated by Django 3.0.3 on 2020-07-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0020_auto_20200709_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='city',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.City'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='country',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.Country'),
        ),
    ]
