# Generated by Django 3.0.3 on 2020-06-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0020_auto_20200615_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
