# Generated by Django 3.0.3 on 2020-07-27 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0020_auto_20200727_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=300, null=True)),
                ('audio', models.URLField()),
                ('image', models.URLField()),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast')),
            ],
        ),
    ]
