# Generated by Django 3.0.3 on 2020-06-16 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_api', '0021_compaign_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendDate', models.DateField(auto_now=True)),
                ('text', models.TextField()),
                ('readFlag', models.BooleanField(default=False)),
                ('Announcer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast')),
            ],
        ),
    ]
