# Generated by Django 3.0.3 on 2020-07-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0021_podcastepisode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PodcastEpisode',
            new_name='Episodes',
        ),
        migrations.AddField(
            model_name='compaign',
            name='episodes',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.Episodes'),
        ),
    ]
