# Generated by Django 3.0.3 on 2020-07-09 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0021_auto_20200709_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='interests',
        ),
    ]
