# Generated by Django 3.0.3 on 2020-07-27 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0022_auto_20200727_1949'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Episodes',
            new_name='Ep',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='podcast',
        ),
    ]
