# Generated by Django 3.0.3 on 2020-06-16 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0022_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Announcer',
            new_name='announcer',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='Podcast',
            new_name='podcast',
        ),
        migrations.AddField(
            model_name='compaign',
            name='podcast',
            field=models.ForeignKey(default=182, on_delete=django.db.models.deletion.CASCADE, to='data_api.Podcast'),
            preserve_default=False,
        ),
    ]
