# Generated by Django 3.0.3 on 2020-07-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0023_remove_compaign_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='ageGroup',
            field=models.ManyToManyField(blank=True, to='data_api.AgeGroup'),
        ),
    ]
