# Generated by Django 3.0.3 on 2020-06-18 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0023_auto_20200616_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='compaign',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='data_api.Compaign'),
            preserve_default=False,
        ),
    ]
