# Generated by Django 3.0.3 on 2020-07-27 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0023_auto_20200727_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ep',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='ep',
            name='image',
        ),
    ]
