# Generated by Django 3.0.3 on 2020-06-18 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0024_message_compaign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='announcer',
            new_name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='podcast',
        ),
    ]
