# Generated by Django 3.0.3 on 2020-07-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0024_podcast_agegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='targetGender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Gender'),
        ),
    ]
