# Generated by Django 3.0.3 on 2020-07-27 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0024_auto_20200727_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaign',
            name='episodes',
        ),
    ]
