# Generated by Django 3.0.3 on 2020-07-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0025_remove_compaign_episodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='ep',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.Ep'),
        ),
    ]
