# Generated by Django 3.0.3 on 2020-06-18 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0025_auto_20200618_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='compaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='data_api.Compaign'),
        ),
    ]
