# Generated by Django 3.0.3 on 2020-07-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0026_compaign_ep'),
    ]

    operations = [
        migrations.AddField(
            model_name='ep',
            name='audio',
            field=models.URLField(default='www.google.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ep',
            name='image',
            field=models.URLField(default='wwww.google.com'),
            preserve_default=False,
        ),
    ]
