# Generated by Django 3.0.3 on 2020-06-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0026_auto_20200618_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='compaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Compaign'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sendDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
