# Generated by Django 3.0.3 on 2020-07-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0027_auto_20200727_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='advancement',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
