# Generated by Django 3.0.3 on 2020-06-19 15:09

import data_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0027_auto_20200619_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachedFile',
            field=models.FileField(blank=True, upload_to=data_api.models.scramble_uploaded_filename),
        ),
    ]
