# Generated by Django 3.0.3 on 2020-06-19 16:39

import data_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0028_message_attachedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachedFile',
            field=models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_filename),
        ),
    ]
