# Generated by Django 3.0.3 on 2020-07-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0028_auto_20200716_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='ageInterval',
        ),
        migrations.AlterField(
            model_name='podcast',
            name='ageGroup',
            field=models.ManyToManyField(blank=True, null=True, to='data_api.AgeGroup'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='urlFeed',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
