# Generated by Django 3.0.3 on 2020-07-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0030_ecoutes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ecoutes',
            new_name='plays',
        ),
    ]
