# Generated by Django 3.0.3 on 2020-06-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0030_auto_20200620_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachedFileName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
