# Generated by Django 3.0.3 on 2020-07-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0031_auto_20200729_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='plays',
            name='status',
            field=models.CharField(default='current', max_length=25),
        ),
    ]
