# Generated by Django 3.0.3 on 2020-06-20 11:56

import data_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0031_message_attachedfilename'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='profilePicture',
            field=models.ImageField(blank=True, upload_to=data_api.models.scramble_uploaded_filename),
        ),
    ]
