# Generated by Django 3.0.3 on 2020-07-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0031_auto_20200718_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='adText',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
