# Generated by Django 3.0.3 on 2020-07-30 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0032_plays_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='subStatus',
            field=models.IntegerField(default=0),
        ),
    ]
