# Generated by Django 3.0.3 on 2020-07-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0032_compaign_adtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='audioFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='compaign',
            name='audioFileName',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
