# Generated by Django 3.0.3 on 2020-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0033_compaign_substatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaign',
            name='subStatus',
        ),
        migrations.AddField(
            model_name='compaign',
            name='startedExchange',
            field=models.BooleanField(default=False),
        ),
    ]
