# Generated by Django 3.0.3 on 2020-06-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0034_auto_20200620_1307'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
