# Generated by Django 3.0.3 on 2020-09-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0036_auto_20200901_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ep',
            name='name',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='ep',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
    ]
