# Generated by Django 3.0.3 on 2020-07-20 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0037_compaign_pitch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaignattachedfile',
            name='attachedFile',
        ),
        migrations.AlterField(
            model_name='compaignattachedfile',
            name='compaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Compaign'),
        ),
    ]
