# Generated by Django 3.0.3 on 2020-09-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0037_auto_20200901_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ep',
            name='audio',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ep',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ep',
            name='name',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ep',
            name='text',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
