# Generated by Django 3.0.3 on 2020-06-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0037_auto_20200620_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='first_name',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='last_name',
            field=models.CharField(default='a', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='company',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
