# Generated by Django 3.0.3 on 2020-09-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0038_auto_20200901_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notificationsAnnouncer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='notificationsPodcaster',
            field=models.IntegerField(default=0),
        ),
    ]
