# Generated by Django 3.0.3 on 2020-07-20 18:08

import data_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0039_auto_20200720_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='attached',
            name='attachedFile',
            field=models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_filename),
        ),
    ]
