# Generated by Django 3.0.3 on 2020-09-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0039_auto_20200903_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='notificationsAnnouncer',
        ),
        migrations.RemoveField(
            model_name='message',
            name='notificationsPodcaster',
        ),
        migrations.AddField(
            model_name='compaign',
            name='notificationsAnnouncer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='compaign',
            name='notificationsPodcaster',
            field=models.IntegerField(default=0),
        ),
    ]
