# Generated by Django 3.0.3 on 2020-09-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0040_auto_20200903_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sendDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
