# Generated by Django 3.0.3 on 2020-09-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0041_auto_20200909_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='city',
            field=models.ManyToManyField(blank=True, to='data_api.City'),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='country',
            field=models.ManyToManyField(blank=True, to='data_api.Country'),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='ep',
            field=models.ManyToManyField(blank=True, to='data_api.Ep'),
        ),
    ]
