# Generated by Django 3.0.3 on 2020-07-21 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0042_proposition_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='plays',
            new_name='playsProp',
        ),
        migrations.RenameField(
            model_name='proposition',
            old_name='price',
            new_name='priceProp',
        ),
    ]
