# Generated by Django 3.0.3 on 2020-07-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0043_auto_20200721_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposition',
            old_name='playsProp',
            new_name='plays',
        ),
        migrations.RenameField(
            model_name='proposition',
            old_name='priceProp',
            new_name='price',
        ),
    ]
