# Generated by Django 3.0.3 on 2020-09-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0043_auto_20200909_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='adtext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plays', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=25)),
                ('message', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Message')),
            ],
        ),
    ]
