# Generated by Django 3.0.3 on 2020-09-10 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0044_auto_20200910_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adtext',
            old_name='plays',
            new_name='text',
        ),
    ]
