# Generated by Django 3.0.3 on 2020-07-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0045_proposition_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='compaign',
        ),
        migrations.RemoveField(
            model_name='proposition',
            name='sender',
        ),
        migrations.AddField(
            model_name='proposition',
            name='proposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Message'),
        ),
    ]
