# Generated by Django 3.0.3 on 2020-09-20 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0046_auto_20200920_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='street',
        ),
    ]
