# Generated by Django 3.0.3 on 2020-07-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0046_auto_20200722_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='proposition',
        ),
    ]
