# Generated by Django 3.0.3 on 2020-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0047_remove_proposition_proposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default='proposition', max_length=28),
            preserve_default=False,
        ),
    ]
