# Generated by Django 3.0.3 on 2020-09-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0048_auto_20200920_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='company',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
