# Generated by Django 3.0.3 on 2020-07-22 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0049_message_proposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='proposition',
        ),
        migrations.AddField(
            model_name='proposition',
            name='message',
            field=models.ForeignKey(default=73, on_delete=django.db.models.deletion.CASCADE, to='data_api.Message'),
            preserve_default=False,
        ),
    ]
