# Generated by Django 3.0.3 on 2020-11-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0049_auto_20200920_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='ep',
            name='Date',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
