# Generated by Django 3.0.3 on 2020-11-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0050_ep_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ep',
            name='Durée',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
