# Generated by Django 3.0.3 on 2020-07-22 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0050_auto_20200722_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='message',
        ),
    ]
