# Generated by Django 3.0.3 on 2020-07-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0052_proposition_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='proposition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Proposition'),
        ),
    ]
