# Generated by Django 3.0.3 on 2020-07-22 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0053_auto_20200722_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='proposition',
        ),
        migrations.AddField(
            model_name='proposition',
            name='message',
            field=models.OneToOneField(default=73, on_delete=django.db.models.deletion.CASCADE, to='data_api.Message'),
            preserve_default=False,
        ),
    ]
