# Generated by Django 3.0.3 on 2020-07-22 17:23

import data_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0055_auto_20200722_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audioFile', models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_audiofilename)),
                ('audioFileName', models.CharField(blank=True, max_length=128, null=True)),
                ('status', models.IntegerField(choices=[('draft', '0'), ('final', 'final')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='audioFile',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='audioFileName',
        ),
    ]
