# Generated by Django 3.0.3 on 2020-06-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0003_education_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='Education',
        ),
    ]
