# Generated by Django 3.0.3 on 2020-07-01 08:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0006_auto_20200628_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='about',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='author',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='episodesLoadingStatus',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='listenNotesId',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='nb_episodes',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='podcastPicture',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='public',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='podcast',
            name='ageInterval',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='podcast',
            name='city',
            field=models.ManyToManyField(blank=True, to='data_api.City'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='country',
            field=models.ManyToManyField(blank=True, to='data_api.Country'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='interests',
            field=models.ManyToManyField(blank=True, to='data_api.Interest'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='nbPlays',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='urlFeed',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
