# Generated by Django 3.0.3 on 2020-07-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0007_auto_20200701_0807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52)),
            ],
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='tags',
        ),
        migrations.AddField(
            model_name='podcast',
            name='tags',
            field=models.ManyToManyField(blank=True, to='data_api.Tag'),
        ),
    ]
