# Generated by Django 3.0.3 on 2020-07-01 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0009_podcast_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='ageInterval',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='city',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='country',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='interests',
        ),
    ]
