# Generated by Django 3.0.3 on 2020-07-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0011_auto_20200701_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='city',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='country',
        ),
    ]
