# Generated by Django 3.0.3 on 2020-07-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0012_auto_20200701_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
    ]
