# Generated by Django 3.0.3 on 2020-07-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0013_remove_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='city',
            field=models.ManyToManyField(blank=True, to='data_api.City'),
        ),
        migrations.AddField(
            model_name='podcast',
            name='country',
            field=models.ManyToManyField(blank=True, to='data_api.Country'),
        ),
    ]
