# Generated by Django 3.0.3 on 2020-07-07 13:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0016_auto_20200707_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40, null=True), blank=True, null=True, size=None),
        ),
    ]
