# Generated by Django 3.0.3 on 2020-07-09 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0022_remove_podcast_interests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaign',
            name='interests',
        ),
    ]
