# Generated by Django 3.0.3 on 2020-07-13 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0025_podcast_targetgender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compaign',
            name='ageMax',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='ageMin',
        ),
        migrations.RemoveField(
            model_name='compaign',
            name='educationLevel',
        ),
    ]
