# Generated by Django 3.0.3 on 2020-07-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0026_auto_20200713_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='editor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
