# Generated by Django 3.0.3 on 2020-07-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0027_auto_20200716_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='editor',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
