# Generated by Django 3.0.3 on 2020-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0029_auto_20200717_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compaign',
            name='targetReach',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
