# Generated by Django 3.0.3 on 2020-07-18 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0030_auto_20200718_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compaign',
            old_name='Price',
            new_name='plays',
        ),
        migrations.RenameField(
            model_name='compaign',
            old_name='targetReach',
            new_name='price',
        ),
    ]
