# Generated by Django 3.0.3 on 2020-07-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0033_auto_20200719_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='audioFileName',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
