# Generated by Django 3.0.3 on 2020-07-20 15:51

import data_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0034_auto_20200719_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='statusNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='compaign',
            name='audioFile',
            field=models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_audiofilename),
        ),
    ]
