# Generated by Django 3.0.3 on 2020-07-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0036_compaign_actionfor'),
    ]

    operations = [
        migrations.AddField(
            model_name='compaign',
            name='pitch',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
