# Generated by Django 3.0.3 on 2020-07-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0038_auto_20200720_1802'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompaignAttachedFile',
            new_name='attached',
        ),
    ]
