# Generated by Django 3.0.3 on 2020-07-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0040_attached_attachedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='proposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('plays', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('compaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_api.Compaign')),
            ],
        ),
    ]
