# Generated by Django 3.0.3 on 2020-07-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0041_proposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='comment',
            field=models.TextField(default='tt', max_length=1200),
            preserve_default=False,
        ),
    ]
