# Generated by Django 3.0.3 on 2020-07-22 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0054_auto_20200722_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposition',
            name='message',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='data_api.Message'),
        ),
    ]
