# Generated by Django 3.0.3 on 2020-07-22 17:43

import data_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_api', '0056_auto_20200722_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioFile',
        ),
        migrations.AddField(
            model_name='compaign',
            name='audioFile',
            field=models.FileField(blank=True, null=True, upload_to=data_api.models.scramble_uploaded_audiofilename),
        ),
    ]
